---
- name: Deploy SSH key to all Mint machines
  hosts: all
  become: true
  gather_facts: false

  vars:
    ansible_ssh_user: admin # Replace with your Mint user (e.g. 'agent', 'manager', etc.)
    ansible_ssh_pass: "{{ vault_ssh_password }}" # only for the first run

  tasks:
    - name: Ensure authorized_keys directory exists
      file:
        path: "/home/{{ ansible_ssh_user }}/.ssh"
        state: directory
        mode: "0700"
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"

    - name: Copy control node's public key to remote authorized_keys
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible_id_rsa.pub') }}"
